---
title: "Patient Clinical Trial Matchup"
author: "Jerome Dixon"
date: "7/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

setwd("~/R/Projects/ORNL")
library(readxl)

```


```{r}

participants <- read_excel("data/participants_data/Dataset2_Sample_Participant_Data_With_Syn_Columns_Marked.xlsx")

```

```{r}

library(httr)
library(jsonlite)
library(dplyr)
library(magrittr)

url <- "https://clinicaltrialsapi.cancer.gov/v1/clinical-trials"

result_clinical_trials <- httr::GET(url)

ct_content <- httr::content(result_clinical_trials, as = 'text')

ct_json <- jsonlite::fromJSON(ct_content)

ct_df <- ct_json$trials

```

```{r}

library(reticulate)
use_condaenv("data-challenge")

```


```{python}

import pkg_resources
installed_packages = pkg_resources.working_set
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
   for i in installed_packages])
print(installed_packages_list)

```
 
```{r}

hemoglobin_rials <- read_excel("data/eligibility_criteria/Dataset1_Hemoglobin_Trials_First.xlsx")


```


